import { migrate, openDb, rowToAsset } from "./db.js";
import { loadEnv } from "./config.js";

export function buildDashboardFromSqlite() {
  const config = loadEnv();
  const db = migrate(openDb());
  try {
    const assets = getAssets(db);
    const update = latestUpdateRun(db);
    const hasData = assets.some((asset) => asset.hasData);
    return {
      meta: {
        version: "0.2.2",
        dataStatus: hasData ? "ready" : "empty",
        hasApiKey: Boolean(config.apiKey),
        lastUpdated: update?.finished_at || null,
        message: hasData
          ? "Cloud snapshot generated by local batch job from SQLite derived metrics."
          : "No SQLite data has been exported yet."
      },
      marketSnapshot: getMarketSnapshot(db, update),
      assets,
      alerts: buildAlerts(assets),
      events: getEvents(db),
      risk: getRisk(assets),
      themeHeat: buildThemeHeat(assets)
    };
  } finally {
    db.close();
  }
}

function getAssets(db) {
  return db.prepare(`
    SELECT a.*, d.as_of, d.score, d.risk_level, d.trend, d.volume_ratio, d.relative_strength,
           d.daily_change, d.five_day_change, d.twenty_day_change, d.price, d.signals_json
    FROM assets a
    LEFT JOIN derived_metrics d ON d.ticker = a.ticker
    WHERE a.enabled = 1
    ORDER BY a.priority, a.ticker
  `).all().map(toApiAsset);
}

function getEvents(db) {
  const eventRows = db.prepare("SELECT * FROM events ORDER BY date DESC LIMIT 50").all();
  const newsEvents = db.prepare(`
    SELECT ticker, published_at as date, '新闻' as type,
           CASE WHEN sentiment = 'negative' THEN 'high' ELSE 'medium' END as importance,
           title as description, source
    FROM news_items
    ORDER BY published_at DESC
    LIMIT 30
  `).all();
  const filingEvents = db.prepare(`
    SELECT ticker, filed_at as date, form_type as type, 'high' as importance,
           COALESCE(description, form_type) as description, source
    FROM filings
    ORDER BY filed_at DESC
    LIMIT 30
  `).all();
  return [...eventRows, ...newsEvents, ...filingEvents].filter((event) => event.date).slice(0, 60);
}

function toApiAsset(row) {
  const base = rowToAsset(row);
  const signals = row.signals_json ? JSON.parse(row.signals_json) : [];
  return {
    ...base,
    hasData: Boolean(row.as_of),
    asOf: row.as_of || null,
    price: row.price,
    dailyChange: row.daily_change,
    fiveDayChange: row.five_day_change,
    twentyDayChange: row.twenty_day_change,
    trend: row.trend || "未更新",
    volumeRatio: row.volume_ratio,
    relativeStrength: row.relative_strength || "未更新",
    score: row.score,
    riskLevel: row.risk_level || "yellow",
    signals,
    nextCatalyst: signals[0]?.label || (row.as_of ? "无触发信号" : "等待首次更新"),
    riskNote: signals[0]?.evidence || (row.as_of ? "价格、量能和趋势已更新；暂无额外动态指标触发。" : "未完成首次更新；请运行 data:update。"),
    insight: row.as_of ? "由本地 SQLite 的行情、新闻和 filings 派生，并发布到云存储。" : "尚无真实行情入库。",
    fundamentals: {
      revenueGrowth: "等待 provider 接入",
      margin: "等待 provider 接入",
      fcf: "等待 provider 接入",
      guidance: "等待 provider 接入"
    },
    valuation: {
      primaryMetric: "等待 provider 接入",
      range: "未更新",
      comment: "估值字段不使用模拟数据。"
    },
    events: signals.map((signal) => signal.label)
  };
}

function latestUpdateRun(db) {
  return db.prepare("SELECT * FROM update_runs ORDER BY id DESC LIMIT 1").get();
}

function getMarketSnapshot(db, update) {
  const row = db.prepare("SELECT * FROM market_snapshots ORDER BY date DESC LIMIT 1").get();
  return row || {
    date: update?.finished_at?.slice(0, 10) || null,
    mode: "Neutral",
    fetched_at: update?.finished_at || null
  };
}

function getRisk(assets) {
  const groups = new Map();
  for (const asset of assets) groups.set(asset.group, (groups.get(asset.group) || 0) + 1);
  const maxGroup = Math.max(0, ...groups.values());
  const redAssets = assets.filter((asset) => asset.riskLevel === "red");
  const yellowAssets = assets.filter((asset) => asset.riskLevel === "yellow");
  return {
    sectorConcentration: assets.length ? Math.round((maxGroup / assets.length) * 100) : 0,
    singleNameExposure: 0,
    portfolioBeta: null,
    cashRatio: null,
    notes: [
      "风险敞口基于本地 batch job 写入的最新 SQLite 派生数据。",
      `${redAssets.length} 个红灯，${yellowAssets.length} 个黄灯；红灯资产优先于总分排序。`
    ]
  };
}

function buildAlerts(assets) {
  return assets
    .flatMap((asset) => asset.signals.slice(0, 2).map((signal) => ({
      level: signal.tone,
      ticker: asset.ticker,
      title: signal.label,
      reason: signal.howToWatch,
      action: signal.referenceRange,
      timestamp: asset.asOf || ""
    })))
    .slice(0, 8);
}

function buildThemeHeat(assets) {
  const byGroup = new Map();
  for (const asset of assets) {
    const bucket = byGroup.get(asset.group) || [];
    bucket.push(asset);
    byGroup.set(asset.group, bucket);
  }
  return Array.from(byGroup, ([name, groupAssets]) => ({
    name,
    value: Math.round(groupAssets.reduce((sum, asset) => sum + (asset.score || 0), 0) / Math.max(1, groupAssets.length)),
    change: Number((groupAssets.reduce((sum, asset) => sum + (asset.twentyDayChange || 0), 0) / Math.max(1, groupAssets.length)).toFixed(1))
  }));
}
