import { put } from "@vercel/blob";
import { buildLiveDashboard } from "../dashboard.js";

export default async function handler(request, response) {
  response.setHeader("Cache-Control", "no-store, no-cache, must-revalidate, max-age=0");

  if (request.method !== "POST") {
    return response.status(405).json({ ok: false, error: "Method not allowed" });
  }

  try {
    const snapshot = await buildLiveDashboard();
    snapshot.meta = {
      ...snapshot.meta,
      message: "Cloud snapshot generated by manual production refresh and stored in Vercel Blob.",
      cloudSource: "manual-refresh",
      refreshedBy: "api/admin/refresh"
    };

    const pathname = process.env.DASHBOARD_BLOB_PATH || "dashboard/latest.json";
    const blob = await put(pathname, JSON.stringify(snapshot, null, 2), {
      access: "public",
      allowOverwrite: true,
      contentType: "application/json",
      cacheControlMaxAge: 60
    });

    return response.status(200).json({
      ok: true,
      updatedAt: snapshot.meta.lastUpdated,
      blobUrl: blob.url,
      pathname,
      price: snapshot.assets.find((asset) => asset.ticker === "SPCX")?.price ?? null,
      asOf: snapshot.assets.find((asset) => asset.ticker === "SPCX")?.asOf ?? null
    });
  } catch (error) {
    return response.status(500).json({
      ok: false,
      error: error instanceof Error ? error.message : "Manual refresh failed"
    });
  }
}
